[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
# Add other networks as needed

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# Add other networks as needed 